### ISSUE TITLE
Codec name or template ValueError 

### ISSUE THREAD

**Issue by netricsa** [liamlangli/vat#1]
Hi,

I exported 31 frames from my file in obj sequence, and executed the build_vat.py after installing the required packages.
After the parsing of obj, there's this error that occurs:

max vertex count 1554
frame count 31
create output texture [2048, 32]
normalizing animation data
save output file
Traceback (most recent call last):
  File "E:\projects\vat-main\build_vat.py", line 150, in <module>
    main('../export/')
  File "E:\projects\vat-main\build_vat.py", line 145, in main
    save_exr(join(output_path, 'vat_vertex_tex.exr'), vertex_tex)
  File "E:\projects\vat-main\build_vat.py", line 54, in save_exr
    imageio.imwrite(filename, data.astype(np.float32))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\imageio\v2.py", line 397, in imwrite
    return file.write(im, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\imageio\plugins\pyav.py", line 634, in write
    self.init_video_stream(codec, fps=fps, pixel_format=out_pixel_format)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\imageio\plugins\pyav.py", line 846, in init_video_stream
    stream = self._container.add_stream(codec, fps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\container\output.pyx", line 61, in av.container.output.OutputContainer.add_stream
ValueError: needs one of codec_name or template

Could it be because I missed any step?

Thank you! :)

**Comment by netricsa** [comment]
My bad. Freeimage was not correctly installed. got it's package install correctly and it gave the output file :)
